### ISSUE TITLE
DB: Get Single Post by ID or Title

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/api-cisc3140-su19#1]
There doesn't seem to be a way to get a post by ID, or just by title.
I'm going to try and make a method to do so, I'll close this if I figure it out.

**Comment by chalshaff12** [comment]
You can do this with all_posts_by(column_name, data_value)
posts_db.all_posts_by('postId', 1)
posts_db.all_posts_by('postTitle', 'Textbooks for Cheap!')

**Comment by Maker-Mark** [comment]
Ahh okay, so it'll just return all the posts that match that, but since it's by title, and title is unique, it should just be one. Gothca! 
Thank you
