### ISSUE TITLE
DataBase: "You have an error in your SQL syntax" when adding a comment.

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/api-cisc3140-su19#2]
I am implementing the following feature, and am getting a SQL syntax response. See screenshots below.
![image](https://user-images.githubusercontent.com/40143016/62975618-cb287780-bde8-11e9-815f-e07556ffde19.png)

![image](https://user-images.githubusercontent.com/40143016/62975609-c6fc5a00-bde8-11e9-9801-d85b72e46719.png)

**Comment by Maker-Mark** [comment]
INSERT INTO comments (text, postId, parentId, userId) VALUES ('Okay listen here, I will not be buying the textbook,
-BOB', 1, NULL, (select id from users where username = 'BOB'))
127.0.0.1 - - [13/Aug/2019 17:15:44] "POST /add-comment/ HTTP/1.1" 200 -

**Comment by chalshaff12** [comment]
Fixed and fixed!
